### ISSUE TITLE
Inconsistency with Hapi when responding with a null

### ISSUE THREAD

**Issue by dominykas** [hapijs/nes#106]
When sending a `reply(null)` via Nes, the client will receive `'null'`, which will be parsed into a `null`.

When sending a `reply(null)` via HTTP, the actual request body will be an empty string, `JSON.parse('')` throws.

This might be an issue if Nes is to be used with XHR interchangeably.

I think the correct fix is for Nes to send an empty string for empty responses, just like Hapi does for `No Content` (although `No Content` and `null` may just be separate cases and this may have to be fixed in Hapi instead...) I can probably PR this myself - just need to know which way to go...

**Comment by hueniverse** [comment]
nes deals with the raw object passed to `reply()` since it doesn't use HTTP. The type is preserved in nes while it is sometimes lost via HTTP. I am not sure what's the right solution here. I need to think about it.

**Comment by jtlapp** [comment]
Since the proper behavior is undocumented (other than in code), I guess it's best to never return `null` and instead always put possibly-null reply data in an object envelope. E.g.

```js
return reply({
    data: myDataEvenIfNull
});
```

**Comment by jtlapp** [comment]
My google searches for best practices reveal an ongoing battle over whether status code 204 or 404 is more appropriate, with some suggesting my above approach as the safe way out.

**Comment by jtlapp** [comment]
Except the returning an empty data envelope isn't helpful for PUTing or DELETEing, where no data is expected in return. It seems like we need a status code that means "endpoint was found but resource at that endpoint was not found."

404 ambiguously means "either client or server is broken because that endpoint doesn't exist" or "server appears to be working but there may have been a race condition because the resource is no longer available." The former case should report an internal error, the latter case might be handled gracefully as a race condition of simultaneous user actions.

**Comment by jtlapp** [comment]
But if the resource ID is in the URL, as in `http://myserver.com/api/monster/132`, then 404 would be the correct response. Okay, I'm returning 404 instead of returning `null` or a null data envelope.

Maybe we should resolve this issue by disallowing the ambiguous return value of `null`?

**Comment by mtharrison** [comment]
I'm not sure I'm inclined to change anything here. Nes will return `null` payload for any of the following cases:

- returning `null` from a handler
- returning `h.response()`
- returning `h.continue`

Because the nes protocol is based on JSON everything has to be (un)serializable that way, however HTTP doesn't provide the same guarantees. Nes also distinguishes between an empty string and a null response, unlike HTTP.

If you respond with a string/buffer/stream in your handler, nes will set `payload` equal to that string but if you try to parse it as JSON from HTTP response, you're also going to get an exception thrown. In those cases you just need to check the response header and only parse JSON if it's actually `application/json`. Unless you're always responding with JSON, I don't think it's safe to assume you can `JSON.parse()` your response.

**Comment by dominykas** [comment]
My only concern was that the endpoints become not interchangeable and produce a different result in the client when used over Nes and over HTTP. If you think that is not a part of, eh, Nes featureset, i.e. not something Nes strives to achieve - it can be addressed with a client side wrapper by whoever needs it.

I'll check the string case and I'll check how Hapi responds when explicitly setting `application/json` with a `null` response.

**Comment by mtharrison** [comment]
I think in that case it will respond with empty body and set the header regardless. It's still invalid JSON in that case. If you take nes out of this picture altogether, responding with `null` isn't going to give you something you can safely parse with `JSON.parse()`.

**Comment by mtharrison** [comment]
Sure, that would be a hapi issue though.

**Comment by hueniverse** [comment]
This would be a breaking protocol change, but we could add a special response meaning no body.

**Comment by dominykas** [comment]
Hapi does respond with an empty body whether you give it an empty string or a `null` and regardless if you set the header.

From the consumer perspective, nes client behaves as if `{ json: true }` option is passed into Wreck, i.e. when response is `null` - it returns a `null`. It does behave slightly differently to Wreck when response is an empty string `''` - nes will (correctly?) return '', whereas Wreck will convert it to `null` regardless of content-type (which is their problem, I guess).

I guess this is what most people desire, even though internally the `payload` is different at the protocol level.

Would it then make sense to add some unit tests for empty/null responses with/without headers (I can do that later)?

Or maybe nothing needs to be done and this is all irrelevant anyways.

Here's the tests I ran: https://gist.github.com/dominykas/bfdfea6d10c1bc56b2c1fffc3074d70c

**Comment by hueniverse** [comment]
Tests documenting this are always good to have, so that changes in the future are easier to catch. This wasn't a problem for me the way I used nes. But I am no opposed to changing it in a breaking or non-breaking way.
