### ISSUE TITLE
Client side error in Safari

### ISSUE THREAD

**Issue by Dinfyru** [hapijs/nes#166]
error: http://joxi.ru/EA4NZjpczMPBmb
file: https://revizor-game.ru/gamepublic/js/client.js

**Comment by sirgallifrey** [comment]
This happens most likely because you are not transpiling your code to make it ES5 compatible. Client.js contais code that is not supported by some browsers, like: `const, let, () => {}`

If you are using webpack to bundle your client-side code have a look at this: https://github.com/babel/babel-loader

**Comment by Dinfyru** [comment]
@sirgallifrey this file from Nes - https://github.com/hapijs/nes/blob/master/lib/client.js

**Comment by Dinfyru** [comment]
and i don't use webpack

**Comment by sirgallifrey** [comment]
> @sirgallifrey this file from Nes - https://github.com/hapijs/nes/blob/master/lib/client.js

I understand that,  but even if this file is not yours you can transpile it at your build process

> and i don't use webpack

webpack is not a requirement, it's just a way to do it. You can use babel to transpile this file in many ways, that's gona depend on your build process.

Transpiling this file yourself is the fastest way to solve this, but is very reasonable that such file could be already transpiled into the package, for this you can send a PR. I can do it, but only if a maintainer comment here that he or she will accept a PR, otherwise I would be wasting everyone's time. :P

**Comment by sirgallifrey** [comment]
never mind me, this has already been done... Seeing the files only trough github made me miss that /dist/client.js is already transpiled. Now i really wasted everyones time...

Are you sure you are getting this file and not the source one? Can you give more details of the error or the error stack on the first error?

**Comment by Dinfyru** [comment]
http://take.ms/HfFgG - error
http://take.ms/05P9f - line

**Comment by sirgallifrey** [comment]
Now I see.

You are using the **source** file. This file `lib/client.js` is the **source** file and it is not meant to be used directly, so you should not be using this one.

You should be using the one found at `dist/client.js` but you wont find this file on the repo because there are only source files in here. If you get this package trough **npm** you will receive the `dist/client.js` and it'll be available trough `require('nes/client') `

If you are just cloning this repository to your machine and grabbing this one file that concern to you, it you be required to generate the **dist** file.

How can you do that? 

let's **assume** you cloned this project to your computer like so:

```bash
git clone https://github.com/hapijs/nes.git
```

So now you need to navigate to the Nes folder and install the **npm** dependencies:

```bash
cd nes
npm install
```

With the dependencies installed you need to run the build command
```bash
npm run build-client
``` 

If you have **not cloned** this repo, nor have you installed nes through **npm**  we need to know more about how are you using this file and how it landed in your project to assist you further
