### ISSUE TITLE
Error in Safari only: Connection requires authentication

### ISSUE THREAD

**Issue by prathameshpalyekar** [hapijs/nes#174]
I am using cookie based authentication which works fine in chrome but gives Error Unauthorised i.e says connection requires authentication. Its occurs half of the time.
I am calling authConnect to connect client.
Following is code 

`function connect() {
    socket.connect({}, (err) => {
        if (err) {
            disconnectSocket(err);
            console.log(err);
            return false;
        }
    });
}`

`function authConnect() {
    axios({
        url: '/nes/auth',
        method: 'GET'
    }).then((xhrResponse) => {
        connect();
    }, (err) => {
        console.log(err);
        Alert.error('Socket authentication failed. Please refresh and try again.')
    });
}`

`export default function disconnectSocket(err) {
	socket.disconnect(function(willReconnect, log) {
    	if (err) {
            connect();
        }
    });
}`

Note:  I am getting authorisation success from backend

**Comment by hueniverse** [comment]
I know Safari has some issues with setting cookies in redirections. bell has some code to deal with this. Not sure if it's related or not. I'll leave this open for a bit in case someone else has an idea but I won't be able to help.

**Comment by ldesplat** [comment]
Yes, first of all you have to be careful with the SameSite setting of cookies. If set with `SameSite=Strict` Hapi's default, then a behavior like that will happen when somebody clicks a link to your website. Setting it to `SameSite:Lax` then this won't be the case. This could explain a half discrepancy.

Safari also had some kind of similar protections going on before any of the browsers implemented SameSite, where it will not send the cookies for very specific cases. So bell had to detect that scenario and do a refresh of the page to get Safari to give up its cookie.

Actual Spec: https://tools.ietf.org/html/draft-west-first-party-cookies-07
More readable article: https://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/

Otherwise, it does not look like you're doing CORS stuff here which could explain this too.

You'll have to explain in more details as to your setup if it's not any of this.

**Comment by prathameshpalyekar** [comment]
@hueniverse @ldesplat Thanks for quick reply. I went through the docs you have provided but I am still facing the issue. I will give a try once more and will try to come up with more info for you.
